# top 5 rows, Add totals, Create readable context
# 📊 Data → Insight Converter


class ReportAgent:

    def generate_report(self, llm_output):
        report = f"""
        SMART CITY ANALYTICS REPORT
        -----------------------------
        {llm_output}
        -----------------------------
        Generated by UrbanBot Intelligence System
        """
        return report
